subinclude("//build_defs:js")

js_library(
    name = "layout",
    srcs = [
        "Stack.jsx",
        "Inline.jsx",
    ],
    entry_point = "index.jsx",
    deps = [
        "//third_party/js:react",
        "//examples/react/components/layout/styles",
    ],
    visibility = ["//examples/react/..."],
)
