subinclude("//build_defs:js")

css_module(
    name = "styles",
    module_name = "styles",
    entry_point = "index.js",
    srcs = [
        "Stack.module.css",
        "Inline.module.css",
    ],
    visibility = ["//examples/react/..."],
)
