subinclude("//build_defs:js")

js_library(
    name = "app",
    srcs = [
        "App.jsx",
    ],
    entry_point = "index.jsx",
    deps = [
        "//third_party/js:react",
        "//third_party/js:react-router",
        "//examples/react/styles",
        "//examples/react/components/button",
        "//examples/react/components/layout",
    ],
    visibility = ["//examples/react/..."],
)
