subinclude("//build_defs:js")

js_library(
    name = "styles",
    srcs = [
        "index.js",
    ],
    deps = [
        ":css",
    ],
    visibility = ["//examples/react/..."],
)

css_file(
    name = "css",
    srcs = [
        "app.css",
        "card.css",
    ],
)
