subinclude("//build_defs:js")

js_library(
    name = "button",
    srcs = [
        "Button.jsx",
    ],
    entry_point = "index.jsx",
    deps = [
        "//third_party/js:react",
        "//third_party/js:react-dom",
        "//examples/react/components/button/styles",
    ],
    visibility = ["//examples/react/..."],
)
